describe('link Start/Arrival Points', () => {

    it('link Start/Arrival Point', () => {
        cy.login('dqy0828@gmail.com','123456789')
        cy.get('.dropdown-toggle').click()
        cy.get('.dropdown-menu > .modify-page').click()
        cy.url().should('include', '/myHikeList')
        cy.get(':nth-child(5) > .card > .card-header > :nth-child(1) > .col-md-4 > .d-flex > .btn-group > .btn-primary').click()
        cy.url().should('include', '/modifyHike')
        cy.get('#modify-tab-handler-tab-LinkStartEndpoints').click()
        cy.get('.linkStartBtn').click()
        cy.get('.startHut').select('A6e9rYeUqbiVdWx3rCNX')
        cy.get('.startPark').select('cn01kJR3vrflh2ioVMdY')
        cy.get('.startConfirmBtn').click()
        cy.get('.linkArrivalBtn').click()
        cy.get('.arrivalPark').select('cn01kJR3vrflh2ioVMdY')
        cy.get('.arrivalHut').select('A6e9rYeUqbiVdWx3rCNX')
        cy.get('.arrivalConfirmBtn').click()
        cy.get('.btn-success').contains('Save Changes').click()
        cy.contains('Latitude')
        cy.contains('Longitude')
        cy.contains('Altitude')
        cy.contains('Name')
        cy.contains('Action')
        cy.contains('Start point')
        cy.contains('44.11341291723514')
        cy.contains('8.06621312580597')
        cy.contains('233.892067')
        cy.contains('Veravo Park Star')
        cy.contains('End point')
        cy.contains('44.113446900517765')
        cy.contains('8.06554931951915')
        cy.contains('233.892067')
        cy.contains('Veravo Hut Star')
        cy.logout()
    })

    it('link Start Point', () => {
        cy.login('dqy0828@gmail.com','123456789')
        cy.get('.dropdown-toggle').click()
        cy.get('.dropdown-menu > .modify-page').click()
        cy.url().should('include', '/myHikeList')
        cy.get(':nth-child(5) > .card > .card-header > :nth-child(1) > .col-md-4 > .d-flex > .btn-group > .btn-primary').click()
        cy.url().should('include', '/modifyHike')
        cy.get('#modify-tab-handler-tab-LinkStartEndpoints').click()
        cy.get('.linkStartBtn').click()
        cy.get('.startHut').select('A6e9rYeUqbiVdWx3rCNX')
        cy.get('.startPark').select('cn01kJR3vrflh2ioVMdY')
        cy.get('.startConfirmBtn').click()
        cy.get('.btn-success').contains('Save Changes').click()
        cy.contains('Latitude')
        cy.contains('Longitude')
        cy.contains('Altitude')
        cy.contains('Name')
        cy.contains('Action')
        cy.contains('Start point')
        cy.contains('44.11341291723514')
        cy.contains('8.06621312580597')
        cy.contains('233.892067')
        cy.contains('Veravo Park Star')
        cy.contains('End point')
        cy.logout()
    })

    it('link Start/Arrival Point', () => {
        cy.login('dqy0828@gmail.com','123456789')
        cy.get('.dropdown-toggle').click()
        cy.get('.dropdown-menu > .modify-page').click()
        cy.url().should('include', '/myHikeList')
        cy.get(':nth-child(5) > .card > .card-header > :nth-child(1) > .col-md-4 > .d-flex > .btn-group > .btn-primary').click()
        cy.url().should('include', '/modifyHike')
        cy.get('#modify-tab-handler-tab-LinkStartEndpoints').click()
        cy.get('.linkArrivalBtn').click()
        cy.get('.arrivalPark').select('cn01kJR3vrflh2ioVMdY')
        cy.get('.arrivalHut').select('A6e9rYeUqbiVdWx3rCNX')
        cy.get('.arrivalConfirmBtn').click()
        cy.get('.btn-success').contains('Save Changes').click()
        cy.contains('Latitude')
        cy.contains('Longitude')
        cy.contains('Altitude')
        cy.contains('Name')
        cy.contains('Action')
        cy.contains('Start point')
        cy.contains('End point')
        cy.contains('44.113446900517765')
        cy.contains('8.06554931951915')
        cy.contains('233.892067')
        cy.contains('Veravo Hut Star')
        cy.logout()
    })
})