describe('update condition', () => {

    it('login by hut worker to update condition ', () => { 
        cy.visit('http://localhost:3000/')
        cy.contains('Sign In').click()
        cy.url().should('include', '/login')
        cy.get('.email-input').type('s300179@studenti.polito.it')
        cy.get('.password-input').type('123456789')
        cy.get('.loginbtn').click()
        cy.url().should('include', '/')
        cy.get('.mb-1').click()
        cy.contains('Hike Condition').click()
        cy.url().should('include', '/hikeCondition')
        cy.contains('Title')
        cy.contains('Location')
        cy.contains('Description')
        cy.contains('Condition')
        cy.contains('Condition Detail')
        cy.contains('Difficulty')
        cy.contains('Length')
        cy.contains('Ascent')
        cy.contains('Estimated Time')
        cy.contains('Show more info').click()
        cy.contains('Hike')
        cy.contains('Description')
        cy.contains('Difficulty')
        cy.contains('Length')
        cy.contains('Ascent')
        cy.contains('Estimated Time')
        cy.get('.closebtn').click()
        cy.get('.update_cond').click()
        cy.contains('Update Condition')
        cy.contains('Condition')
        cy.contains('Condition Detail')
        cy.get('.condition-input').select('partly blocked').should('have.value', 'partly blocked')
        cy.get('.condition-detail-input').type('Repair').should('have.value', 'Repair')
        cy.contains('Confirm').click()
        cy.contains('Update Condition Feedback')
        cy.contains('Update Condition Success!')
        cy.get('.close-feedback').click()
        cy.contains('partly blocked')
        cy.contains('Repair')
        cy.get('.mb-1').click()
        cy.contains('Sign out').click()
        cy.url().should('include', '/')

    })
})
